[package]
name = "nomarch-bench"
version = "0.1.0"
authors = ["andre"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goose = "*"
serde = "*"
serde_json = "*"
uuid = { version = "0.8", features = ["serde", "v4"] }